export const USERNAME_UPDATE="USERNAME_UPDATE";
export const PASSWORD_UPDATE="PASSWORD_UPDATE";
export const REQUEST_LOGIN="REQUEST_LOGIN";
export const LOGIN_RETURNED="LOGIN_RETURNED";
export const UNAUTHORIZED_EXCEPTION="UNAUTHORIZED_EXCEPTION";
export const SET_LOGGED_IN="SET_LOGGED_IN";
export const SET_LOGGED_OUT="SET_LOGGED_OUT";

export const GET_CURRENT_USER="GET_CURRENT_USER";
export const GET_CURRENT_USER_RETURNED="GET_CURRENT_USER_RETURNED";

export const GET_MEETING_TYPES="GET_MEETING_TYPES";
export const GET_MEETING_TYPES_RETURNED="GET_MEETING_TYPES_RETURNED";

export const NEW_ADDRESS_PROP_UPDATE="NEW_ADDRESS_PROP_UPDATE";
export const NEW_ADDRESS_REQUEST_INSERT="ADDRESS_REQUEST_INSERT";
export const NEW_ADDRESS_REQUEST_INSERT_RETURNED="NEW_ADDRESS_REQUEST_INSERT_RETURNED";
export const NEW_ADDRESS_CLEAR="NEW_ADDRESS_CLEAR";

export const ALL_ADDRESSES_REQUEST_ALL="ADDRESS_DATA_REQUEST_ALL";
export const ALL_ADDRESSES_REQUEST_ALL_RETURNED="REQUEST_ALL_RETURNED";
export const ALL_ADDRESSES_REQUEST_DELETE="ALL_ADDRESSES_REQUEST_DELETE";
export const ALL_ADDRESSES_DELETE_RETURNED="ALL_ADDRESSES_DELETE_RETURNED";


export const NEW_MEETING_TIME_TOGGLE_MERIDIEM="NEW_MEETING_TOGGLE_MERIDIEM";
export const NEW_MEETING_TIME_CYCLE_DAY="NEW_MEETING_TIME_CYCLE_DAY";
export const NEW_MEETING_TIME_CYCLE_HOUR="NEW_MEETING_TIME_CYCLE_HOUR";
export const NEW_MEETING_TIME_CYCLE_MINUTE="NEW_MEETING_TIME_CYCLE_MINUTE";
export const CLEAR_NEW_MEETING_TIME="CLEAR_NEW_MEETING_TIME";
export const ADD_MEETING_TYPE_TO_NEW_MEETING_TIME="ADD_MEETING_TYPE_TO_NEW_MEETING_TIME";
export const REMOVE_MEETING_TYPE_FROM_NEW_MEETING_TIME="REMOVE_MEETING_TYPE_FROM_NEW_MEETING_TIME";

export const ADD_NEW_MEETING_TIME_TO_NEW_MEETING="ADD_NEW_MEETING_TIME_TO_NEW_MEETING";
export const SET_NEW_MEETINGS_ADDRESS="SET_NEW_MEETINGS_ADDRESS";
export const UPDATE_NEW_MEETING_NAME="UPDATE_NEW_MEETING_NAME";
export const REMOVE_MEETING_TIME_FROM_NEW_MEETING_BY_INDEX="REMOVE_MEETING_TIME_FROM_NEW_MEETING_BY_INDEX";

export const POPULATE_SELECT_BOX="POPULATE_SELECT_BOX";
export const CHANGE_SELECTED="CHANGE_SELECTED";
export const MEETING_TYPE_SELECT_BOX_SET_IS_FRESH="MEETING_TYPE_SELECT_BOX_SET_IS_FRESH";


export const GENERIC_GET_ALL_DATA_RETURNED="GENERIC_GET_ALL_DATA_RETURNED";
export const GENERIC_GET_ALL_DATA_REQUEST="GENERIC_GET_ALL_DATA_REQUEST";
