export const USERNAME_UPDATE="USERNAME_UPDATE";
export const PASSWORD_UPDATE="PASSWORD_UPDATE";
export const REQUEST_LOGIN="REQUEST_LOGIN";
export const LOGIN_RETURNED="LOGIN_RETURNED";
export const UNAUTHORIZED_EXCEPTION="UNAUTHORIZED_EXCEPTION";
export const SET_LOGGED_IN="SET_LOGGED_IN";
export const SET_LOGGED_OUT="SET_LOGGED_OUT";

export const GET_CURRENT_USER="GET_CURRENT_USER";
export const GET_CURRENT_USER_RETURNED="GET_CURRENT_USER_RETURNED";

export const GET_MEETING_TYPES="GET_MEETING_TYPES";
export const GET_MEETING_TYPES_RETURNED="GET_MEETING_TYPES_RETURNED";

export const NEW_ADDRESS_PROP_UPDATE="NEW_ADDRESS_PROP_UPDATE";
export const NEW_ADDRESS_REQUEST_INSERT="ADDRESS_REQUEST_INSERT";
export const NEW_ADDRESS_REQUEST_INSERT_RETURNED="NEW_ADDRESS_REQUEST_INSERT_RETURNED";
export const NEW_ADDRESS_CLEAR="NEW_ADDRESS_CLEAR";

export const ALL_ADDRESSES_REQUEST_ALL="ADDRESS_DATA_REQUEST_ALL";
export const ALL_ADDRESSES_REQUEST_ALL_RETURNED="REQUEST_ALL_RETURNED";
export const ALL_ADDRESSES_REQUEST_DELETE="ALL_ADDRESSES_REQUEST_DELETE";
export const ALL_ADDRESSES_DELETE_RETURNED="ALL_ADDRESSES_DELETE_RETURNED";

